### ISSUE TITLE
social media analytics app

### ISSUE THREAD

**Issue by spences10** [RobDWaller/robdwaller.github.io#1]
Hey @RobDWaller, 

As you dont have an [ama](https://github.com/sindresorhus/ama) I'll ask this here :smile: 

I'd like to know a bit more about your social media analytics app from your site if you don't mind sharing :+1:

**Comment by RobDWaller** [comment]
Should have responded to this sooner, bit busy.

What do you want to know? 

It's basically a simple Twitter Anti-Spam tool.

**Comment by spences10** [comment]
>Should have responded to this sooner, bit busy.
>
>What do you want to know?
>
>It's basically a simple Twitter Anti-Spam tool.

Cool, 

I understand you're busy so, thanks for the reply :+1: 

* What was the technology stack?
* How did it define what was spam or not?
  * Spam accounts or spam tweets?

**Comment by RobDWaller** [comment]
It was a Lamp Stack, needs a rebuild though as the Twitter API is being updated in Jan.

It's a very simple algorithm that looks for a data fingerprint that a lot of spam accounts share.

For example follows to followers is often an important relationship.

It's not too complicated.

**Comment by spences10** [comment]
>For example follows to followers is often an important relationship.

Yes, I'd like to know a bit more about this actually, I know there's a ratio to follow

Not that I'm asking you to divulge any sensitive information just like to know for my own purposes
